#!/usr/bin/env bash
#author: Dhimant Thanki 
#Date:Saturday 03 August 2019 08:35:48 PM IST
#Description: This script will check for the reachability of multiple IPs

#set -x
FILE="/home/jack/professional-scripts/hosts"

for IPs in `cat $FILE`
do
	ping -w2 $IPs >& /dev/null ; status=$([ "$?" -eq 0 ] && echo "$IPs is reachable" || echo "$IPs is not reachable")
	echo $status
done
